AllCops:
  TargetRubyVersion: 2.5

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'lib/bson-objectid-to-uuid.rb'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'lib/bson/object_id/uuid_convertable/version.rb'

Style/Documentation:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
# SupportedStyles: space, no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
